//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMonitor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Station
    {
        public int StationID { get; set; }
        public string StationCode { get; set; }
        public string Name { get; set; }
        public string CompanyCode { get; set; }
        public int StationType { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
        public string ShortName { get; set; }
    }
}
